[project]
name = "foolad-sang-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jdatetime>=5.2.0",
    "openpyxl>=3.1.5",
    "typer>=0.20.0",
]
